# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json

include:
  - project: tools/shared-pipelines
    ref: v7.14.5
    file: /base/base.yaml
    inputs:
      ignored_licenses:
        - BlueOak-1.0.0
        - LGPL-3.0-or-later
        - SEE LICENSE IN LICENSE
        - MIT-0
  - project: tools/shared-pipelines
    ref: v7.14.5
    file: /nodejs/nodejs.yaml

# Prepare
prepare-precache:
  extends: .prepare-nodejs-precache

# Audit
audit-licenses:
  extends: .audit-nodejs-licenses

audit-security:
  extends: .audit-nodejs-security

# Analysis
analysis-lint:
  extends: .analysis-nodejs-lint

analysis-format:
  extends: .analysis-nodejs-format

analysis-typescript:
  extends: .analysis-nodejs-typescript

build:
  extends: .build-nodejs-pnpm

publish-preview:
  extends: .publish-nodejs-pnpm-preview

publish-production:
  extends: .publish-nodejs-pnpm-production

# Release
release-prepare-mr:
  extends:
    - .release-prepare-mr

release-tag:
  extends:
    - .release-tag
