# Dependency age
minimumReleaseAge: 4320 # 3 days - same as renovate
minimumReleaseAgeExclude:
  - "@foldland/*"
  - "@strapi/*"

registries:
  default: https://registry.npmjs.org/
  "@foldland": https://npm.registry.foldland.io/

# Dependency resolution
savePrefix: "^"
resolutionMode: "highest"
strictPeerDependencies: true
preferFrozenLockfile: true

# node version
engineStrict: true
ignorePnpmfile: true

# Security
blockExoticSubdeps: true
hoist: false
hoistWorkspacePackages: false
verifyDepsBeforeRun: "install"

allowBuilds:
  "@swc/core": false
  core-js-pure: false
  esbuild: false
  sharp: false


# broken strapi peers
peerDependencyRules:
  allowedVersions:
    codemirror: 5.65.21

overrides:
  vite@<=6.4.2: ^6.4.3
