FROM mcr.microsoft.com/devcontainers/typescript-node:24@sha256:4c09888a2acdaf619daa79d2e811329536450a1045be9243fe03d4b02c81e91e

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install gnupg2
