FROM mcr.microsoft.com/devcontainers/typescript-node:24@sha256:fb4652b1a9bca94d31eaa4d8446176e96350a7644b4633675612ce6b2c1e2b1f

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install gnupg2
